version: "3"
services:
  client-nextjs:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./pages:/app/pages
    environment:
      - NEXT_PUBLIC_IS_TRUE=true
    env_file:
      - ./.env

